export const fakeCat6Data: {
  DocumentDate: string;
  DocumentNumber: string;
  StaffID: number;
  TripType: string;
  StartTime: string;
  EndTime: string;
  BusinessTripType: string;
  PlaceOfDeparture: string;
  DepartureAirport: string;
  LandTrasportationTypeA: string;
  DestinationAirport: string;
  ThirdCountryTransferDestination: string;
  LandTrasportationTypeB: string;
  NumberOfNightsStayed: number;
}[] = [
  {
    DocumentDate: '2025-01-02',
    DocumentNumber: 'LYV-HR-BT250100001',
    StaffID: 21974,
    TripType: 'Round Trip',
    StartTime: '2025-02-15',
    EndTime: '2025-03-01',
    BusinessTripType: 'Overseas business trip to third-party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'SGN',
    LandTrasportationTypeA: 'Company Shuttle Bus',
    DestinationAirport: 'NUE',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTrasportationTypeB: 'Car',
    NumberOfNightsStayed: 14,
  },
  // {
  //   DocumentDate: '2025-01-02',
  //   DocumentNumber: 'LYV-HR-BT250100002',
  //   StaffID: 26032,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-02-15',
  //   EndTime: '2025-02-28',
  //   BusinessTripType: 'Overseas business trip to third-party entities',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'NUE',
  //   ThirdCountryTransferDestination:
  //     'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
  //   LandTrasportationTypeB: 'Car',
  //   NumberOfNightsStayed: 13,
  // },
  // {
  //   DocumentDate: '2025-01-21',
  //   DocumentNumber: 'LYV-HR-BT250100021',
  //   StaffID: 33886,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-03-23',
  //   EndTime: '2025-03-27',
  //   BusinessTripType: 'Overseas business trip to third-party entities',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'CAN',
  //   ThirdCountryTransferDestination:
  //     '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
  //   LandTrasportationTypeB: '高鐵',
  //   NumberOfNightsStayed: 4,
  // },
  // {
  //   DocumentDate: '2025-01-21',
  //   DocumentNumber: 'LYV-HR-BT250100022',
  //   StaffID: 33886,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-02-10',
  //   EndTime: '2025-02-21',
  //   BusinessTripType: 'Overseas business trip to third-party entities',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'NUE',
  //   ThirdCountryTransferDestination:
  //     'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
  //   LandTrasportationTypeB: 'Car',
  //   NumberOfNightsStayed: 11,
  // },
  // {
  //   DocumentDate: '2025-02-15',
  //   DocumentNumber: 'LYV-HR-BT250200024',
  //   StaffID: 24293,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-03-01',
  //   EndTime: '2025-03-08',
  //   BusinessTripType: 'Overseas business trip within the group',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'RGN',
  //   ThirdCountryTransferDestination:
  //     'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
  //   LandTrasportationTypeB: 'Company Shuttle Bus',
  //   NumberOfNightsStayed: 7,
  // },
  // {
  //   DocumentDate: '2025-02-16',
  //   DocumentNumber: 'LYV-HR-BT250200025',
  //   StaffID: 26886,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-03-01',
  //   EndTime: '2025-03-08',
  //   BusinessTripType: 'Overseas business trip within the group',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'RGN',
  //   ThirdCountryTransferDestination:
  //     'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
  //   LandTrasportationTypeB: 'Company Shuttle Bus',
  //   NumberOfNightsStayed: 7,
  // },
  // {
  //   DocumentDate: '2025-03-07',
  //   DocumentNumber: 'LYV-HR-BT250300006',
  //   StaffID: 31791,
  //   TripType: 'Round Trip',
  //   StartTime: '2025-04-08',
  //   EndTime: '2025-04-26',
  //   BusinessTripType: 'Overseas business trip to third-party entities',
  //   PlaceOfDeparture:
  //     '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
  //   DepartureAirport: 'SGN',
  //   LandTrasportationTypeA: 'Company Shuttle Bus',
  //   DestinationAirport: 'SUB',
  //   ThirdCountryTransferDestination:
  //     'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
  //   LandTrasportationTypeB: 'Company Shuttle Bus',
  //   NumberOfNightsStayed: 18,
  // },
];

// [
//   {
//     DocumentDate: '2025-01-02',
//     DocumentNumber: 'LYV-HR-BT250100001',
//     StaffID: 21974,
//     TripType: 'Round Trip',
//     StartTime: '2025-02-15',
//     EndTime: '2025-03-01',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 14,
//   },
//   {
//     DocumentDate: '2025-01-02',
//     DocumentNumber: 'LYV-HR-BT250100002',
//     StaffID: 26032,
//     TripType: 'Round Trip',
//     StartTime: '2025-02-15',
//     EndTime: '2025-02-28',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 13,
//   },
//   {
//     DocumentDate: '2025-01-04',
//     DocumentNumber: 'LYV-HR-BT250100003',
//     StaffID: 21258,
//     TripType: 'Round Trip',
//     StartTime: '2025-03-24',
//     EndTime: '2025-03-27',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'CAN',
//     ThirdCountryTransferDestination:
//       '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 3,
//   },
//   {
//     DocumentDate: '2025-01-21',
//     DocumentNumber: 'LYV-HR-BT250100021',
//     StaffID: 33886,
//     TripType: 'Round Trip',
//     StartTime: '2025-03-23',
//     EndTime: '2025-03-27',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'CAN',
//     ThirdCountryTransferDestination:
//       '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 4,
//   },
//   {
//     DocumentDate: '2025-01-21',
//     DocumentNumber: 'LYV-HR-BT250100022',
//     StaffID: 33886,
//     TripType: 'Round Trip',
//     StartTime: '2025-02-10',
//     EndTime: '2025-02-21',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 11,
//   },
//   {
//     DocumentDate: '2025-02-15',
//     DocumentNumber: 'LYV-HR-BT250200024',
//     StaffID: 24293,
//     TripType: 'Round Trip',
//     StartTime: '2025-03-01',
//     EndTime: '2025-03-08',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 7,
//   },
//   {
//     DocumentDate: '2025-02-16',
//     DocumentNumber: 'LYV-HR-BT250200025',
//     StaffID: 26886,
//     TripType: 'Round Trip',
//     StartTime: '2025-03-01',
//     EndTime: '2025-03-08',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 7,
//   },
//   {
//     DocumentDate: '2025-03-07',
//     DocumentNumber: 'LYV-HR-BT250300006',
//     StaffID: 31791,
//     TripType: 'Round Trip',
//     StartTime: '2025-04-08',
//     EndTime: '2025-04-26',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SUB',
//     ThirdCountryTransferDestination:
//       'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 18,
//   },
//   {
//     DocumentDate: '2025-03-08',
//     DocumentNumber: 'LYV-HR-BT250300007',
//     StaffID: 51187,
//     TripType: 'Round Trip',
//     StartTime: '2025-04-08',
//     EndTime: '2025-04-16',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SUB',
//     ThirdCountryTransferDestination:
//       'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 8,
//   },
//   {
//     DocumentDate: '2025-03-12',
//     DocumentNumber: 'LYV-HR-BT250300019',
//     StaffID: 33821,
//     TripType: 'Round Trip',
//     StartTime: '2025-03-23',
//     EndTime: '2025-03-27',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'CAN',
//     ThirdCountryTransferDestination:
//       '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 4,
//   },
//   {
//     DocumentDate: '2025-03-25',
//     DocumentNumber: 'LYV-HR-BT250300033',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-05-05',
//     EndTime: '2025-05-09',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 4,
//   },
//   {
//     DocumentDate: '2025-03-26',
//     DocumentNumber: 'LYV-HR-BT250300034',
//     StaffID: 51187,
//     TripType: 'Round Trip',
//     StartTime: '2025-05-05',
//     EndTime: '2025-05-09',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 4,
//   },
//   {
//     DocumentDate: '2025-04-11',
//     DocumentNumber: 'LYV-HR-BT250400007',
//     StaffID: 32282,
//     TripType: 'Round Trip',
//     StartTime: '2025-05-06',
//     EndTime: '2025-05-09',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 3,
//   },
//   {
//     DocumentDate: '2025-05-08',
//     DocumentNumber: 'LYV-HR-BT250500012',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-05-18',
//     EndTime: '2025-05-23',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SUB',
//     ThirdCountryTransferDestination:
//       'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 5,
//   },
//   {
//     DocumentDate: '2025-06-09',
//     DocumentNumber: 'LYV-HR-BT250600002',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-06-12',
//     EndTime: '2025-06-13',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NKG',
//     ThirdCountryTransferDestination:
//       '中國江苏省苏州市吴中区现代大道 邮政编码: 215121',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 1,
//   },
//   {
//     DocumentDate: '2025-06-11',
//     DocumentNumber: 'LYV-HR-BT250600003',
//     StaffID: 51187,
//     TripType: 'Round Trip',
//     StartTime: '2025-06-12',
//     EndTime: '2025-06-14',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'HKG',
//     ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 2,
//   },
//   {
//     DocumentDate: '2025-06-18',
//     DocumentNumber: 'LYV-HR-BT250600013',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-16',
//     EndTime: '2025-07-19',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SRG',
//     ThirdCountryTransferDestination:
//       'Jl. Padma Boulevard No.B5/3, Tambakharjo, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149, Indonesia',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 3,
//   },
//   {
//     DocumentDate: '2025-06-30',
//     DocumentNumber: 'LYV-HR-BT250600041',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-02',
//     EndTime: '2025-07-03',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SZX',
//     ThirdCountryTransferDestination: '中國東莞市 邮政编码: 523900',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 1,
//   },
//   {
//     DocumentDate: '2025-07-01',
//     DocumentNumber: 'LYV-HR-BT250700001',
//     StaffID: 33107,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-16',
//     EndTime: '2025-08-31',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 15,
//   },
//   {
//     DocumentDate: '2025-07-03',
//     DocumentNumber: 'LYV-HR-BT250700006',
//     StaffID: 33886,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-26',
//     EndTime: '2025-08-07',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'LAX',
//     ThirdCountryTransferDestination:
//       '110 E 9th St, Los Angeles, CA 90079, United States',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 12,
//   },
//   {
//     DocumentDate: '2025-07-03',
//     DocumentNumber: 'LYV-HR-BT250700008',
//     StaffID: 34748,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-16',
//     EndTime: '2025-08-31',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 15,
//   },
//   {
//     DocumentDate: '2025-07-03',
//     DocumentNumber: 'LYV-HR-BT250700010',
//     StaffID: 33173,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-19',
//     EndTime: '2025-08-31',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 12,
//   },
//   {
//     DocumentDate: '2025-07-04',
//     DocumentNumber: 'LYV-HR-BT250700015',
//     StaffID: 21974,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-09',
//     EndTime: '2025-08-16',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 7,
//   },
//   {
//     DocumentDate: '2025-07-05',
//     DocumentNumber: 'LYV-HR-BT250700016',
//     StaffID: 25910,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-09',
//     EndTime: '2025-08-16',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 7,
//   },
//   {
//     DocumentDate: '2025-07-05',
//     DocumentNumber: 'LYV-HR-BT250700017',
//     StaffID: 26032,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-09',
//     EndTime: '2025-08-16',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 7,
//   },
//   {
//     DocumentDate: '2025-07-09',
//     DocumentNumber: 'LYV-HR-BT250700023',
//     StaffID: 33886,
//     TripType: 'Round Trip',
//     StartTime: '2025-08-16',
//     EndTime: '2025-08-25',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'NUE',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 9,
//   },
//   {
//     DocumentDate: '2025-07-23',
//     DocumentNumber: 'LYV-HR-BT250700029',
//     StaffID: 193,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-26',
//     EndTime: '2025-08-07',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'LAX',
//     ThirdCountryTransferDestination:
//       '110 E 9th St, Los Angeles, CA 90079, United States',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 12,
//   },
//   {
//     DocumentDate: '2025-07-23',
//     DocumentNumber: 'LYV-HR-BT250700030',
//     StaffID: 33885,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-26',
//     EndTime: '2025-08-07',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'LAX',
//     ThirdCountryTransferDestination:
//       '110 E 9th St, Los Angeles, CA 90079, United States',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 12,
//   },
//   {
//     DocumentDate: '2025-07-25',
//     DocumentNumber: 'LYV-HR-BT250700031',
//     StaffID: 25733,
//     TripType: 'Round Trip',
//     StartTime: '2025-07-26',
//     EndTime: '2025-08-07',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'LAX',
//     ThirdCountryTransferDestination:
//       '110 E 9th St, Los Angeles, CA 90079, United States',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 12,
//   },
//   {
//     DocumentDate: '2025-08-14',
//     DocumentNumber: 'LYV-HR-BT250800017',
//     StaffID: 26886,
//     TripType: 'Round Trip',
//     StartTime: '2025-09-04',
//     EndTime: '2025-09-13',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 9,
//   },
//   {
//     DocumentDate: '2025-08-28',
//     DocumentNumber: 'LYV-HR-BT250800026',
//     StaffID: 32282,
//     TripType: 'Round Trip',
//     StartTime: '2025-09-17',
//     EndTime: '2025-09-18',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'TPE',
//     ThirdCountryTransferDestination: '300台灣新竹市東區光復路二段321號',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 1,
//   },
//   {
//     DocumentDate: '2025-09-30',
//     DocumentNumber: 'LYV-HR-BT250900021',
//     StaffID: 54,
//     TripType: 'Round Trip',
//     StartTime: '2025-11-10',
//     EndTime: '2025-11-13',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'SZX',
//     ThirdCountryTransferDestination:
//       'Courtyard Shenzhen Northwest No 6259 Baoan Avenue, Baoan District, Shenzhen, Guangdong, China (518103)',
//     LandTrasportationTypeB: '高鐵',
//     NumberOfNightsStayed: 3,
//   },
//   {
//     DocumentDate: '2025-10-21',
//     DocumentNumber: 'LYV-HR-BT251000022',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-10-27',
//     EndTime: '2025-10-30',
//     BusinessTripType: 'Overseas business trip within the group',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'RGN',
//     ThirdCountryTransferDestination:
//       'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
//     LandTrasportationTypeB: 'Company Shuttle Bus',
//     NumberOfNightsStayed: 3,
//   },
//   {
//     DocumentDate: '2025-10-27',
//     DocumentNumber: 'LYV-HR-BT251000024',
//     StaffID: 33886,
//     TripType: 'Round Trip',
//     StartTime: '2025-11-02',
//     EndTime: '2025-11-03',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'HKG',
//     ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 1,
//   },
//   {
//     DocumentDate: '2025-10-28',
//     DocumentNumber: 'LYV-HR-BT251000025',
//     StaffID: 27560,
//     TripType: 'Round Trip',
//     StartTime: '2025-11-02',
//     EndTime: '2025-11-03',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'HKG',
//     ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 1,
//   },
//   {
//     DocumentDate: '2025-10-28',
//     DocumentNumber: 'LYV-HR-BT251000027',
//     StaffID: 175,
//     TripType: 'Round Trip',
//     StartTime: '2025-11-02',
//     EndTime: '2025-11-03',
//     BusinessTripType: 'Overseas business trip to third-party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'SGN',
//     LandTrasportationTypeA: 'Company Shuttle Bus',
//     DestinationAirport: 'HKG',
//     ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
//     LandTrasportationTypeB: 'Car',
//     NumberOfNightsStayed: 1,
//   },
// ];
