export interface AutoCMSCat6Data {
  DocumentDate: string;
  DocumentNumber: string;
  StaffID: number;
  TripType: string;
  StartTime: string;
  EndTime: string;
  BusinessTripType: string;
  PlaceOfDeparture: string;
  DepartureAirport: string;
  LandTransportDistanceA: string;
  LandTrasportationTypeA: string;
  DestinationAirport: string;
  ThirdCountryTransferDestination: string;
  LandTransportDistanceB: string;
  LandTrasportationTypeB: string;
  Destination2: string;
  Destination3: string;
  Destination4: string;
  Destination5: string;
  Destination6: string;
  LandTransportDistance: string;
  LandTrasportationType: string;
  AirTransportDistance: string;
  NumberOfNightsStayed: number;
}

// export const fakeCat6Data: AutoCMSCat6Data[] = [
//   {
//     DocumentDate: '2025-01-02',
//     DocumentNumber: 'LYV-HR-BT250100001',
//     StaffID: 21974,
//     TripType: 'Round Trip',
//     StartTime: '2025-02-15',
//     EndTime: '2025-03-01',
//     BusinessTripType: 'Overseas business trip to third party entities',
//     PlaceOfDeparture:
//       '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
//     DepartureAirport: 'Tan Son Nhat International Airport',
//     LandTransportDistanceA: 'API Auto calculagte',
//     LandTrasportationTypeA: 'Company Shuttle Car',
//     DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
//     ThirdCountryTransferDestination:
//       'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
//     LandTransportDistanceB: 'API Auto calculate',
//     LandTrasportationTypeB: 'Car',
//     Destination2: '',
//     Destination3: '',
//     Destination4: '',
//     Destination5: '',
//     Destination6: '',
//     LandTransportDistance: '',
//     LandTrasportationType: '',
//     AirTransportDistance: 'API Auto calculate',
//     NumberOfNightsStayed: 14,
//   },
// ];

export const fakeCat6Data: AutoCMSCat6Data[] = [
  {
    DocumentDate: '2025-01-02',
    DocumentNumber: 'LYV-HR-BT250100001',
    StaffID: 21974,
    TripType: 'Round Trip',
    StartTime: '2025-02-15',
    EndTime: '2025-03-01',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 14,
  },
  {
    DocumentDate: '2025-01-02',
    DocumentNumber: 'LYV-HR-BT250100002',
    StaffID: 26032,
    TripType: 'Round Trip',
    StartTime: '2025-02-15',
    EndTime: '2025-02-28',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 13,
  },
  {
    DocumentDate: '2025-01-04',
    DocumentNumber: 'LYV-HR-BT250100003',
    StaffID: 21258,
    TripType: 'Round Trip',
    StartTime: '2025-03-24',
    EndTime: '2025-03-27',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Guangzhou Baiyun International Airport',
    ThirdCountryTransferDestination:
      '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 3,
  },
  {
    DocumentDate: '2025-01-21',
    DocumentNumber: 'LYV-HR-BT250100021',
    StaffID: 33886,
    TripType: 'Round Trip',
    StartTime: '2025-03-23',
    EndTime: '2025-03-27',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Guangzhou Baiyun International Airport',
    ThirdCountryTransferDestination:
      '中國广东省广州市 North, 百顺南路30号 邮政编码: 510442',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 4,
  },
  {
    DocumentDate: '2025-01-21',
    DocumentNumber: 'LYV-HR-BT250100022',
    StaffID: 33886,
    TripType: 'Round Trip',
    StartTime: '2025-02-10',
    EndTime: '2025-02-21',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 11,
  },
  {
    DocumentDate: '2025-02-15',
    DocumentNumber: 'LYV-HR-BT250200024',
    StaffID: 24293,
    TripType: 'Round Trip',
    StartTime: '2025-03-01',
    EndTime: '2025-03-08',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 7,
  },
  {
    DocumentDate: '2025-02-16',
    DocumentNumber: 'LYV-HR-BT250200025',
    StaffID: 26886,
    TripType: 'Round Trip',
    StartTime: '2025-03-01',
    EndTime: '2025-03-08',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 7,
  },
  {
    DocumentDate: '2025-03-07',
    DocumentNumber: 'LYV-HR-BT250300006',
    StaffID: 31791,
    TripType: 'Round Trip',
    StartTime: '2025-04-08',
    EndTime: '2025-04-26',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Juanda International Airport',
    ThirdCountryTransferDestination:
      'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 18,
  },
  {
    DocumentDate: '2025-03-08',
    DocumentNumber: 'LYV-HR-BT250300007',
    StaffID: 51187,
    TripType: 'Round Trip',
    StartTime: '2025-04-08',
    EndTime: '2025-04-16',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Juanda International Airport',
    ThirdCountryTransferDestination:
      'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 8,
  },
  {
    DocumentDate: '2025-03-12',
    DocumentNumber: 'LYV-HR-BT250300019',
    StaffID: 33821,
    TripType: 'Round Trip',
    StartTime: '2025-03-23',
    EndTime: '2025-03-27',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Guangzhou Baiyun International Airport',
    ThirdCountryTransferDestination:
      '中國广东省广州市 North, 百顺南路30号 邮政编码 510442',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 4,
  },
  {
    DocumentDate: '2025-03-25',
    DocumentNumber: 'LYV-HR-BT250300033',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-05-05',
    EndTime: '2025-05-09',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 4,
  },
  {
    DocumentDate: '2025-03-26',
    DocumentNumber: 'LYV-HR-BT250300034',
    StaffID: 51187,
    TripType: 'Round Trip',
    StartTime: '2025-05-05',
    EndTime: '2025-05-09',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 4,
  },
  {
    DocumentDate: '2025-04-11',
    DocumentNumber: 'LYV-HR-BT250400007',
    StaffID: 32282,
    TripType: 'Round Trip',
    StartTime: '2025-05-06',
    EndTime: '2025-05-09',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 3,
  },
  {
    DocumentDate: '2025-05-08',
    DocumentNumber: 'LYV-HR-BT250500012',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-05-18',
    EndTime: '2025-05-23',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Juanda International Airport',
    ThirdCountryTransferDestination:
      'Jl. Raya Mojoagung No.Km. 71, Buduran, Jogoloyo, Kec. Peterongan, Kabupaten Jombang, Jawa Timur 61483印尼',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 5,
  },
  {
    DocumentDate: '2025-06-09',
    DocumentNumber: 'LYV-HR-BT250600002',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-06-12',
    EndTime: '2025-06-13',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nanjing Lukou International Airport',
    ThirdCountryTransferDestination:
      '中國江苏省苏州市吴中区现代大道 邮政编码 215121',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
  {
    DocumentDate: '2025-06-11',
    DocumentNumber: 'LYV-HR-BT250600003',
    StaffID: 51187,
    TripType: 'Round Trip',
    StartTime: '2025-06-12',
    EndTime: '2025-06-14',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Hong Kong International Airport',
    ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 2,
  },
  {
    DocumentDate: '2025-06-18',
    DocumentNumber: 'LYV-HR-BT250600013',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-07-16',
    EndTime: '2025-07-19',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Achmad Yani International Airport',
    ThirdCountryTransferDestination:
      'Jl. Padma Boulevard No.B5\/3, Tambakharjo, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149, Indonesia',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 3,
  },
  {
    DocumentDate: '2025-06-30',
    DocumentNumber: 'LYV-HR-BT250600041',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-07-02',
    EndTime: '2025-07-03',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Shenzhen Bao\'an International Airport',
    ThirdCountryTransferDestination: '中國東莞市 邮政编码 523900',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
  {
    DocumentDate: '2025-07-01',
    DocumentNumber: 'LYV-HR-BT250700001',
    StaffID: 33107,
    TripType: 'Round Trip',
    StartTime: '2025-08-16',
    EndTime: '2025-08-31',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 15,
  },
  {
    DocumentDate: '2025-07-03',
    DocumentNumber: 'LYV-HR-BT250700006',
    StaffID: 33886,
    TripType: 'Round Trip',
    StartTime: '2025-07-26',
    EndTime: '2025-08-07',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Los Angeles International Airport',
    ThirdCountryTransferDestination:
      '110 E 9th St, Los Angeles, CA 90079, United States',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 12,
  },
  {
    DocumentDate: '2025-07-03',
    DocumentNumber: 'LYV-HR-BT250700008',
    StaffID: 34748,
    TripType: 'Round Trip',
    StartTime: '2025-08-16',
    EndTime: '2025-08-31',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 15,
  },
  {
    DocumentDate: '2025-07-03',
    DocumentNumber: 'LYV-HR-BT250700010',
    StaffID: 33173,
    TripType: 'Round Trip',
    StartTime: '2025-08-19',
    EndTime: '2025-08-31',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 12,
  },
  {
    DocumentDate: '2025-07-04',
    DocumentNumber: 'LYV-HR-BT250700015',
    StaffID: 21974,
    TripType: 'Round Trip',
    StartTime: '2025-08-09',
    EndTime: '2025-08-16',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 7,
  },
  {
    DocumentDate: '2025-07-05',
    DocumentNumber: 'LYV-HR-BT250700016',
    StaffID: 25910,
    TripType: 'Round Trip',
    StartTime: '2025-08-09',
    EndTime: '2025-08-16',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 7,
  },
  {
    DocumentDate: '2025-07-05',
    DocumentNumber: 'LYV-HR-BT250700017',
    StaffID: 26032,
    TripType: 'Round Trip',
    StartTime: '2025-08-09',
    EndTime: '2025-08-16',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 7,
  },
  {
    DocumentDate: '2025-07-09',
    DocumentNumber: 'LYV-HR-BT250700023',
    StaffID: 33886,
    TripType: 'Round Trip',
    StartTime: '2025-08-16',
    EndTime: '2025-08-25',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Nuremberg Airport (Albrecht Dürer Airport Nürnberg)',
    ThirdCountryTransferDestination:
      'Adi-Dassler-Straße 1, 91074 Herzogenaurach, Germany',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 9,
  },
  {
    DocumentDate: '2025-07-23',
    DocumentNumber: 'LYV-HR-BT250700029',
    StaffID: 193,
    TripType: 'Round Trip',
    StartTime: '2025-07-26',
    EndTime: '2025-08-07',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Los Angeles International Airport',
    ThirdCountryTransferDestination:
      '110 E 9th St, Los Angeles, CA 90079, United States',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 12,
  },
  {
    DocumentDate: '2025-07-23',
    DocumentNumber: 'LYV-HR-BT250700030',
    StaffID: 33885,
    TripType: 'Round Trip',
    StartTime: '2025-07-26',
    EndTime: '2025-08-07',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Los Angeles International Airport',
    ThirdCountryTransferDestination:
      '110 E 9th St, Los Angeles, CA 90079, United States',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 12,
  },
  {
    DocumentDate: '2025-07-25',
    DocumentNumber: 'LYV-HR-BT250700031',
    StaffID: 25733,
    TripType: 'Round Trip',
    StartTime: '2025-07-26',
    EndTime: '2025-08-07',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Los Angeles International Airport',
    ThirdCountryTransferDestination:
      '110 E 9th St, Los Angeles, CA 90079, United States',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 12,
  },
  {
    DocumentDate: '2025-08-14',
    DocumentNumber: 'LYV-HR-BT250800017',
    StaffID: 26886,
    TripType: 'Round Trip',
    StartTime: '2025-09-04',
    EndTime: '2025-09-13',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 9,
  },
  {
    DocumentDate: '2025-08-28',
    DocumentNumber: 'LYV-HR-BT250800026',
    StaffID: 32282,
    TripType: 'Round Trip',
    StartTime: '2025-09-17',
    EndTime: '2025-09-18',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Taiwan Taoyuan International Airport',
    ThirdCountryTransferDestination: '300台灣新竹市東區光復路二段321號',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
  {
    DocumentDate: '2025-09-30',
    DocumentNumber: 'LYV-HR-BT250900021',
    StaffID: 54,
    TripType: 'Round Trip',
    StartTime: '2025-11-10',
    EndTime: '2025-11-13',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Shenzhen Bao\'an International Airport',
    ThirdCountryTransferDestination:
      'Courtyard Shenzhen Northwest No 6259\nBaoan Avenue, Baoan District, Shenzhen,\nGuangdong, China (518103)',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: '高鐵',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 3,
  },
  {
    DocumentDate: '2025-10-21',
    DocumentNumber: 'LYV-HR-BT251000022',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-10-27',
    EndTime: '2025-10-30',
    BusinessTripType: 'Overseas business trip within the group',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Yangon International Airport',
    ThirdCountryTransferDestination:
      'Plot No.X3-X6, Block No.20, Sabei Street, Anawrahta Industrial Zone, Hlaingtharya Township, Yangon Region, Myanmar - Myanmar',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Company Shuttle Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 3,
  },
  {
    DocumentDate: '2025-10-27',
    DocumentNumber: 'LYV-HR-BT251000024',
    StaffID: 33886,
    TripType: 'Round Trip',
    StartTime: '2025-11-02',
    EndTime: '2025-11-03',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Hong Kong International Airport',
    ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
  {
    DocumentDate: '2025-10-28',
    DocumentNumber: 'LYV-HR-BT251000025',
    StaffID: 27560,
    TripType: 'Round Trip',
    StartTime: '2025-11-02',
    EndTime: '2025-11-03',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Hong Kong International Airport',
    ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
  {
    DocumentDate: '2025-10-28',
    DocumentNumber: 'LYV-HR-BT251000027',
    StaffID: 175,
    TripType: 'Round Trip',
    StartTime: '2025-11-02',
    EndTime: '2025-11-03',
    BusinessTripType: 'Overseas business trip to third party entities',
    PlaceOfDeparture:
      '3-5 Đ. Tên Lửa, An Lạc, Bình Tân, Thành phố Hồ Chí Minh 763430越南',
    DepartureAirport: 'Tan Son Nhat International Airport',
    LandTransportDistanceA: 'API Auto calculagte',
    LandTrasportationTypeA: 'Company Shuttle Car',
    DestinationAirport: 'Hong Kong International Airport',
    ThirdCountryTransferDestination: '77 Hoi Bun Rd, Kwun Tong, Hong Kong',
    LandTransportDistanceB: 'API Auto calculate',
    LandTrasportationTypeB: 'Car',
    Destination2: '',
    Destination3: '',
    Destination4: '',
    Destination5: '',
    Destination6: '',
    LandTransportDistance: '',
    LandTrasportationType: '',
    AirTransportDistance: 'API Auto calculate',
    NumberOfNightsStayed: 1,
  },
];
